<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9b977619-209a-4138-a0d1-d681a43f88e7</elementGuidId>
    <imagePath></imagePath>
    <name>input_postal_code</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/form[1]/div[1]/div[3]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#postal-code</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'postal-code') and equals(@name,'postalCode') and equals(@class,'input_error form_input')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>input_error form_input</value>
        <webElementGuid>e30d2a09-64db-4cba-946a-b2af4a2d4421</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>postal-code</value>
        <webElementGuid>13529f52-3e34-47f2-b7d1-48a9aa4935c2</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>postalCode</value>
        <webElementGuid>9e53f947-e71c-45ac-8cfa-d87bb0b13d62</webElementGuid>
    </webElementProperties>
</WebElementEntity>