<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e404fb11-42ca-4584-89b6-7ddb61260b16</elementGuidId>
    <imagePath></imagePath>
    <name>input_continue</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/form[1]/div[2]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>form</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'continue') and equals(@name,'continue') and equals(@class,'submit-button btn btn_primary cart_button btn_action')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>submit-button btn btn_primary cart_button btn_action</value>
        <webElementGuid>dea9ed4d-b02f-4c57-91e0-deddb61540bd</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>continue</value>
        <webElementGuid>29e7221e-b63b-44d1-93fe-cf451434308a</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>continue</value>
        <webElementGuid>aebe0833-eae5-4f28-9bc6-6031f99a8d4e</webElementGuid>
    </webElementProperties>
</WebElementEntity>